### PR TITLE
Initial creation.

### PR DESCRIPTION
**Pull request by zmoore-usgs**

### CODE REVIEW

**Comment by mhines-usgs** [comment]
i get the same issue that Travis does, fyi, 404 from artifactory

**Comment by isuftin** [comment]
The artifact does not seem to exist in Artifactory

https://cida.usgs.gov/artifactory/webapp/#/artifacts/browse/tree/General/aqcu-maven-snapshots/gov/usgs/aqcu

https://cida.usgs.gov/artifactory/webapp/#/artifacts/browse/tree/General/aqcu-maven-centralized/gov/usgs/aqcu

**Comment by kmschoep-usgs** [comment]
the report code hasn't been merged yet.

**Comment by zmoore-usgs** [comment]
Whoops yeah sorry, meant to add a comment saying that the build would fail until the report has been built

**Comment by kmschoep-usgs** [comment]
There is now a java artifact, but I can't seem to kick off a new travis build to clear the failure.

**Comment by zmoore-usgs** [comment]
🎉

**Pull request merged**
